# Generated by Django 5.1.2 on 2024-11-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_site', '0002_remove_hotel_hotel_stars_hotel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Рейтинг'),
        ),
    ]
